/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

/**
 *
 * @author Ana Ruth
 */
public class Familia extends javax.swing.JFrame {

    /**
     * Creates new form Familia
     */
    public Familia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sbcargatexto = new javax.swing.JButton();
        sobreescritura = new javax.swing.JButton();
        nombrePapa = new javax.swing.JTextField();
        nombreHijo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bitacora = new javax.swing.JTextArea();
        salir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        mensaje = new javax.swing.JTextField();
        sbcarganumero = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombreMama = new javax.swing.JTextField();
        sobreescrotura2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nombreHija = new javax.swing.JTextField();
        Sobreesctritura3 = new javax.swing.JButton();
        sobreesctritura4 = new javax.swing.JButton();
        sbcarga2 = new javax.swing.JButton();
        sbvarga3 = new javax.swing.JButton();
        sbcarga4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sbcargatexto.setText("Sobrecarga Texto");
        sbcargatexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbcargatextoActionPerformed(evt);
            }
        });

        sobreescritura.setText("Sobre escritura");
        sobreescritura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreescrituraActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre Papa");

        jLabel2.setText("Nombre Hijo");

        bitacora.setColumns(20);
        bitacora.setRows(5);
        jScrollPane1.setViewportView(bitacora);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel3.setText("Mensaje");

        sbcarganumero.setText("Sobrecarga Número");
        sbcarganumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbcarganumeroActionPerformed(evt);
            }
        });

        jLabel4.setText("FAMILIA");

        jLabel5.setText("Nombre Mama");

        sobreescrotura2.setText("Sobreescritura 2 ");
        sobreescrotura2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreescrotura2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Nombre Hija");

        Sobreesctritura3.setText("Sobreescritura");
        Sobreesctritura3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sobreesctritura3ActionPerformed(evt);
            }
        });

        sobreesctritura4.setText("Sobreescritura");
        sobreesctritura4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreesctritura4ActionPerformed(evt);
            }
        });

        sbcarga2.setText("Sobrecarga Texto");
        sbcarga2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbcarga2ActionPerformed(evt);
            }
        });

        sbvarga3.setText("Sobrecarga Texto");
        sbvarga3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbvarga3ActionPerformed(evt);
            }
        });

        sbcarga4.setText("Sobrecarga Texto");
        sbcarga4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbcarga4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(sbcarganumero))
                                .addGap(51, 51, 51)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(269, 269, 269)
                                .addComponent(salir))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(nombrePapa, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sobreesctritura3)
                                    .addComponent(sbcargatexto))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sobreescritura)
                                    .addComponent(nombreHijo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(sbcarga2))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreMama, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(sobreesctritura4)
                                    .addComponent(sbvarga3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nombreHija, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sbcarga4)
                                            .addComponent(sobreescrotura2))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreHijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombrePapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreMama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreHija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sobreescritura)
                    .addComponent(sobreescrotura2)
                    .addComponent(Sobreesctritura3)
                    .addComponent(sobreesctritura4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sbcarga4)
                    .addComponent(sbvarga3)
                    .addComponent(sbcarga2)
                    .addComponent(sbcargatexto))
                .addGap(23, 23, 23)
                .addComponent(sbcarganumero)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(salir)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void sbcargatextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbcargatextoActionPerformed
        // TODO add your handling code here:
        Papa p=new Papa();
        p.ponerNombre(nombrePapa.getText());
        String txt = p.decirAlgo(mensaje.getText());
        
        bitacora.append(txt+"\n");
        
    }//GEN-LAST:event_sbcargatextoActionPerformed

    private void sbcarganumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbcarganumeroActionPerformed
        // TODO add your handling code here:
        Papa p=new Papa();
        p.ponerNombre(nombrePapa.getText());
        String txt = p.decirAlgo(Integer.parseInt(mensaje.getText()));
        
        bitacora.append(txt+"\n");
        
    }//GEN-LAST:event_sbcarganumeroActionPerformed

    private void sobreescrituraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreescrituraActionPerformed
        // TODO add your handling code here:
        Hijo h=new Hijo();
        h.ponerNombre(nombreHijo.getText());
        String txt = h.devolverNombre();
        
        bitacora.append(txt+"\n");
    }//GEN-LAST:event_sobreescrituraActionPerformed

    private void sobreescrotura2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreescrotura2ActionPerformed
        // TODO add your handling code here:
        Hija h2=new Hija();
        h2.ponerNombre(nombreHija.getText());
        String txt = h2.devolverNombre();
        
        bitacora.append(txt+"\n");
    }//GEN-LAST:event_sobreescrotura2ActionPerformed

    private void Sobreesctritura3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sobreesctritura3ActionPerformed
        // TODO add your handling code here:
        Papa p1=new Papa();
        p1.ponerNombre(nombrePapa.getText());
        String txt = p1.devolverNombre1();
        
        bitacora.append(txt+"\n");
    }//GEN-LAST:event_Sobreesctritura3ActionPerformed

    private void sobreesctritura4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreesctritura4ActionPerformed
        // TODO add your handling code here:
        Mama m=new Mama();
        m.ponerNombre(nombreMama.getText());
        String txt = m.devolverNombre3();
        
        bitacora.append(txt+"\n");
    }//GEN-LAST:event_sobreesctritura4ActionPerformed

    private void sbcarga2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbcarga2ActionPerformed
        // TODO add your handling code here:
        Hijo h1=new Hijo();
        h1.ponerNombre(nombreHijo.getText());
        String txt = h1.decirAlgo(mensaje.getText());
        
        bitacora.append(txt+"\n");
    }//GEN-LAST:event_sbcarga2ActionPerformed

    private void sbvarga3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbvarga3ActionPerformed
        // TODO add your handling code here:
        Papa p=new Papa();
        p.ponerNombre(nombrePapa.getText());
        String txt = p.decirAlgo(mensaje.getText());
        
        bitacora.append(txt+"\n");
    }//GEN-LAST:event_sbvarga3ActionPerformed

    private void sbcarga4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbcarga4ActionPerformed
        // TODO add your handling code here:
        Papa p=new Papa();
        p.ponerNombre(nombrePapa.getText());
        String txt = p.decirAlgo(mensaje.getText());
        
        bitacora.append(txt+"\n");
    }//GEN-LAST:event_sbcarga4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Familia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Familia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Familia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Familia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Familia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sobreesctritura3;
    private javax.swing.JTextArea bitacora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mensaje;
    private javax.swing.JTextField nombreHija;
    private javax.swing.JTextField nombreHijo;
    private javax.swing.JTextField nombreMama;
    private javax.swing.JTextField nombrePapa;
    private javax.swing.JButton salir;
    private javax.swing.JButton sbcarga2;
    private javax.swing.JButton sbcarga4;
    private javax.swing.JButton sbcarganumero;
    private javax.swing.JButton sbcargatexto;
    private javax.swing.JButton sbvarga3;
    private javax.swing.JButton sobreescritura;
    private javax.swing.JButton sobreescrotura2;
    private javax.swing.JButton sobreesctritura4;
    // End of variables declaration//GEN-END:variables
}
